# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('salario', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
