# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
